services:
  postgres:
    image: 'postgres:17.0'
    env_file: .env
  app:
    image: node:23-alpine
    depends_on:
      - postgres
    command: 'npm run docker-dev'
    working_dir: '/app'
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      NODE_ENV: development
    stdin_open: true
    tty: true